### Task 1

Fix the error

In [25]:
import numpy as np 

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[ 4 10 10]
 [ 1  6  7]
 [ 9  2  5]]
Matrix B:
 [[ 3  6  7]
 [10  8  9]
 [ 6  2  8]]


Write fibonacy function:
 
 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 

In [29]:

def fibonacci (n):
    if n == 0:
        return 0
    if n ==1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
        
fibonacci(3)

2

In [31]:
def print_fibonacis(n):
    a = 0
    b = 1
    for _ in range (n):
        sum = a + b
        a = b 
        b = sum 
        print (sum)
print_fibonacis(6)

1
2
3
5
8
13


In [38]:
n = 7

def even_(n):
    if n%2 == 0:
       return True
    else:
        return False
    
even_(n)

False

In [42]:
n = "Hello"
def find_reverse(n):
    return n[::-1]

find_reverse(n)


'olleH'